# Generated by Django 5.1.6 on 2025-03-07 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tbl_Categoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Cat_nombre', models.CharField(max_length=45)),
                ('Cat_foto', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tbl_Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Usu_nombres', models.CharField(max_length=45)),
                ('Usu_apellidos', models.CharField(max_length=45)),
                ('Usu_email', models.EmailField(max_length=60, unique=True)),
                ('Usu_telefono', models.CharField(max_length=12, unique=True)),
                ('Usu_cargo', models.CharField(max_length=45)),
                ('Usu_area', models.CharField(max_length=45)),
                ('Usu_rol', models.IntegerField()),
                ('Usu_foto', models.CharField(blank=True, max_length=255, null=True)),
                ('Usu_firma', models.CharField(blank=True, max_length=255, null=True)),
                ('Usu_estado', models.BooleanField(default=True)),
                ('Usu_en_linea', models.BooleanField(default=False)),
                ('Usu_contraseña', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tbl_Herramienta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Her_nombre', models.CharField(max_length=45)),
                ('Her_caracteristica1', models.CharField(max_length=60)),
                ('Her_caracteristica2', models.CharField(max_length=60)),
                ('Her_marca', models.CharField(max_length=45)),
                ('Her_stock_inicial', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Her_unidad_medida', models.CharField(max_length=45)),
                ('Her_ubicacion', models.CharField(max_length=35)),
                ('Her_stock_minimo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Her_stock', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Her_costo_unitario', models.IntegerField()),
                ('Her_costo_total', models.IntegerField()),
                ('Her_observaciones', models.TextField(blank=True, null=True)),
                ('Her_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.tbl_categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Tbl_Repuesto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Rep_nombre', models.CharField(max_length=45)),
                ('Rep_caracteristica1', models.CharField(max_length=60)),
                ('Rep_caracteristica2', models.CharField(max_length=60)),
                ('Rep_marca', models.CharField(max_length=45)),
                ('Rep_stock_inicial', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Rep_unidad_medida', models.CharField(max_length=45)),
                ('Rep_ubicacion', models.CharField(max_length=35)),
                ('Rep_stock_minimo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Rep_stock', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Rep_costo_unitario', models.IntegerField()),
                ('Rep_costo_total', models.IntegerField()),
                ('Rep_observaciones', models.TextField(blank=True, null=True)),
                ('Rep_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.tbl_categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Tbl_Prestamo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Pre_cantidad', models.IntegerField()),
                ('Pre_area', models.CharField(max_length=45)),
                ('Pre_maquina', models.CharField(max_length=60)),
                ('Pre_motivo_prestamo', models.TextField()),
                ('Pre_fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('Pre_estado', models.IntegerField()),
                ('Pre_fecha_devolucion', models.DateTimeField(blank=True, null=True)),
                ('Pre_herramienta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.tbl_herramienta')),
                ('Pre_usuario_prestamista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestamos', to='inventario.tbl_usuario')),
                ('Pre_usuario_solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='inventario.tbl_usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Tbl_Movimiento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Mov_tipo', models.CharField(max_length=20)),
                ('Mov_cantidad', models.IntegerField()),
                ('Mov_area', models.CharField(max_length=45)),
                ('Mov_maquina_destino', models.CharField(max_length=45)),
                ('Mov_referencia_compra', models.CharField(max_length=60)),
                ('Mov_costo_unitario', models.IntegerField()),
                ('Mov_costo_total', models.IntegerField()),
                ('Mov_motivo', models.TextField()),
                ('Mov_repuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.tbl_repuesto')),
                ('Mov_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.tbl_usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Tbl_Mensaje',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Men_contenido', models.CharField(max_length=255)),
                ('Men_fecha_enviado', models.DateTimeField(auto_now_add=True)),
                ('Men_fecha_leido', models.DateTimeField(blank=True, null=True)),
                ('Men_eliminar_emisor', models.BooleanField(default=False)),
                ('Men_eliminar_receptor', models.BooleanField(default=False)),
                ('Men_usuario_emisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_enviados', to='inventario.tbl_usuario')),
                ('Men_usuario_receptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_recibidos', to='inventario.tbl_usuario')),
            ],
        ),
    ]
