# Generated by Django 5.1.6 on 2025-03-07 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_mensaje',
            name='Men_usuario_emisor',
        ),
        migrations.RemoveField(
            model_name='tbl_mensaje',
            name='Men_usuario_receptor',
        ),
        migrations.RemoveField(
            model_name='tbl_prestamo',
            name='Pre_usuario_prestamista',
        ),
        migrations.RemoveField(
            model_name='tbl_prestamo',
            name='Pre_usuario_solicitante',
        ),
        migrations.AlterField(
            model_name='tbl_usuario',
            name='Usu_rol',
            field=models.BooleanField(),
        ),
    ]
