# Generated by Django 5.1.6 on 2025-03-07 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_remove_tbl_mensaje_men_usuario_emisor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_prestamo',
            name='Pre_usuario_Solicita',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tbl_prestamo',
            name='Pre_usuario_prestamo',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tbl_herramienta',
            name='Her_stock',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tbl_herramienta',
            name='Her_stock_inicial',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tbl_herramienta',
            name='Her_stock_minimo',
            field=models.IntegerField(),
        ),
    ]
