# Generated by Django 5.1.6 on 2025-03-07 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_tbl_prestamo_pre_usuario_solicita_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_mensaje',
            name='Men_usuario_emisor',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tbl_mensaje',
            name='Men_usuario_receptor',
            field=models.IntegerField(default=0),
        ),
    ]
