# Generated by Django 5.1.6 on 2025-03-08 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_tbl_mensaje_men_usuario_emisor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_mensaje',
            name='Men_tipo',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='tbl_categoria',
            name='Cat_foto',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tbl_herramienta',
            name='Her_costo_total',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='tbl_herramienta',
            name='Her_costo_unitario',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='tbl_herramienta',
            name='Her_stock',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='tbl_herramienta',
            name='Her_stock_inicial',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='tbl_herramienta',
            name='Her_stock_minimo',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='tbl_movimiento',
            name='Mov_cantidad',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='tbl_movimiento',
            name='Mov_costo_total',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='tbl_movimiento',
            name='Mov_costo_unitario',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='tbl_movimiento',
            name='Mov_tipo',
            field=models.CharField(choices=[('Entrada', 'Entrada'), ('Salida', 'Salida')], default='Entrada', max_length=20),
        ),
        migrations.AlterField(
            model_name='tbl_prestamo',
            name='Pre_cantidad',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='tbl_prestamo',
            name='Pre_estado',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='tbl_repuesto',
            name='Rep_costo_total',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='tbl_repuesto',
            name='Rep_costo_unitario',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='tbl_usuario',
            name='Usu_firma',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tbl_usuario',
            name='Usu_foto',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
