# Generated by Django 5.1.6 on 2025-03-10 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_tbl_mensaje_men_tipo_alter_tbl_categoria_cat_foto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_herramienta',
            name='Her_caracteristica2',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='tbl_herramienta',
            name='Her_costo_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='tbl_herramienta',
            name='Her_costo_unitario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='tbl_herramienta',
            name='Her_marca',
            field=models.CharField(blank=True, max_length=45),
        ),
        migrations.AlterField(
            model_name='tbl_mensaje',
            name='Men_tipo',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='tbl_movimiento',
            name='Mov_costo_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='tbl_movimiento',
            name='Mov_costo_unitario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='tbl_movimiento',
            name='Mov_referencia_compra',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='tbl_repuesto',
            name='Rep_caracteristica2',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='tbl_repuesto',
            name='Rep_costo_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='tbl_repuesto',
            name='Rep_costo_unitario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='tbl_repuesto',
            name='Rep_marca',
            field=models.CharField(blank=True, max_length=45),
        ),
        migrations.AlterField(
            model_name='tbl_usuario',
            name='Usu_area',
            field=models.CharField(blank=True, max_length=45),
        ),
        migrations.AlterField(
            model_name='tbl_usuario',
            name='Usu_cargo',
            field=models.CharField(blank=True, max_length=45),
        ),
    ]
