# Generated by Django 5.1.7 on 2025-03-10 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_alter_tbl_herramienta_her_caracteristica2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_herramienta',
            name='Her_imagen',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='tbl_mensaje',
            name='Men_imagen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tbl_repuesto',
            name='Rep_imagen',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='tbl_mensaje',
            name='Men_usuario_emisor',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tbl_mensaje',
            name='Men_usuario_receptor',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tbl_prestamo',
            name='Pre_usuario_Solicita',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tbl_prestamo',
            name='Pre_usuario_prestamo',
            field=models.IntegerField(),
        ),
    ]
