# Generated by Django 5.1.7 on 2025-03-17 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_tbl_herramienta_her_imagen_tbl_mensaje_men_imagen_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_usuario',
            old_name='Usu_contraseña',
            new_name='Usu_contrasena',
        ),
    ]
