# Generated by Django 5.1.7 on 2025-03-17 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_rename_usu_contraseña_tbl_usuario_usu_contrasena'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_prestamo',
            old_name='Pre_usuario_Solicita',
            new_name='Pre_usuario_solicita',
        ),
    ]
