# Generated by Django 5.1.7 on 2025-03-17 20:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0009_rename_pre_usuario_solicita_tbl_prestamo_pre_usuario_solicita'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_usuario',
            name='Usu_fecha_registro',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
