# Generated by Django 5.1.7 on 2025-03-28 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0010_tbl_usuario_usu_fecha_registro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_herramienta',
            name='Her_unidad_medida',
            field=models.CharField(choices=[('UNIDADES', 'UNIDADES'), ('PAQUETES', 'PAQUETES'), ('ROLLOS', 'ROLLOS'), ('KILOS', 'KILOS'), ('GALONES', 'GALONES'), ('METROS', 'METROS'), ('CAJAS', 'CAJAS'), ('CANECA', 'CANECA'), ('LITROS', 'LITROS'), ('GRAMOS', 'GRAMOS'), ('TONELADAS', 'TONELADAS'), ('PIEZAS', 'PIEZAS'), ('METROS CÚBICOS', 'METROS CÚBICOS'), ('MILÍMETROS', 'MILÍMETROS'), ('CENTÍMETROS', 'CENTÍMETROS'), ('JUEGOS', 'JUEGOS'), ('CANTIDADES', 'CANTIDADES'), ('MILLARES', 'MILLARES'), ('TOLVAS', 'TOLVAS'), ('BIDDON', 'BIDDON'), ('TRAMO', 'TRAMO'), ('CARRETE', 'CARRETE')], default='UNIDADES', max_length=45),
        ),
        migrations.AlterField(
            model_name='tbl_repuesto',
            name='Rep_unidad_medida',
            field=models.CharField(choices=[('UNIDADES', 'UNIDADES'), ('PAQUETES', 'PAQUETES'), ('ROLLOS', 'ROLLOS'), ('KILOS', 'KILOS'), ('GALONES', 'GALONES'), ('METROS', 'METROS'), ('CAJAS', 'CAJAS'), ('CANECA', 'CANECA'), ('LITROS', 'LITROS'), ('GRAMOS', 'GRAMOS'), ('TONELADAS', 'TONELADAS'), ('PIEZAS', 'PIEZAS'), ('METROS CÚBICOS', 'METROS CÚBICOS'), ('MILÍMETROS', 'MILÍMETROS'), ('CENTÍMETROS', 'CENTÍMETROS'), ('JUEGOS', 'JUEGOS'), ('CANTIDADES', 'CANTIDADES'), ('MILLARES', 'MILLARES'), ('TOLVAS', 'TOLVAS'), ('BIDDON', 'BIDDON'), ('TRAMO', 'TRAMO'), ('CARRETE', 'CARRETE')], default='UNIDADES', max_length=45),
        ),
    ]
