# Generated by Django 5.1.7 on 2025-04-09 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0011_alter_tbl_herramienta_her_unidad_medida_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_usuario',
            name='Usu_firma',
        ),
    ]
