# Generated by Django 5.1.7 on 2025-04-12 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0012_remove_tbl_usuario_usu_firma'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tbl_Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(max_length=255)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inventario.tbl_usuario')),
            ],
        ),
    ]
