# Generated by Django 5.1.7 on 2025-04-23 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0014_alter_tbl_categoria_cat_foto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_categoria',
            name='Cat_foto',
            field=models.ImageField(blank=True, null=True, upload_to='categorias/'),
        ),
        migrations.AlterField(
            model_name='tbl_herramienta',
            name='Her_imagen',
            field=models.ImageField(blank=True, null=True, upload_to='herramientas/'),
        ),
        migrations.AlterField(
            model_name='tbl_repuesto',
            name='Rep_imagen',
            field=models.ImageField(blank=True, null=True, upload_to='repuestos/'),
        ),
        migrations.AlterField(
            model_name='tbl_usuario',
            name='Usu_foto',
            field=models.ImageField(blank=True, null=True, upload_to='usuarios/'),
        ),
    ]
