# Generated by Django 5.1.7 on 2025-04-24 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0016_tokenrecuperacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_token',
            name='token_hash',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
